from database import Database

print("============ Start Of Test ==============")
testDatabase = Database()
testDatabase.create_tables()

testDatabase.insert_branch("Serangoon Branch", "Fairprice Finest", "67 Serangoon Street", "Serangoon", "10000000")
testDatabase.insert_branch("Jurong West Branch", "Sheng Siong", "67 Jurong West Street", "Jurong West", "10000001")
testDatabase.insert_branch("Bugis Branch", "Cold Storage", "67 Bugis Street", "Bugis", "10000002")
testDatabase.insert_branch("Bugis Branch", "Fairprice Finest", "67 Bugis Street", "Bugis", "10000002")
testDatabase.insert_branch("Bugis Branch", "Sheng Siong", "67 Bugis Street", "Bugis", "10000002")
testDatabase.insert_branch("Bedok Branch", "Cold Storage", "67 Bedok Street", "Bedok", "10000003")
testDatabase.insert_branch("AMK Branch", "Sheng Siong", "67 AMK Street", "AMK", "10000004")
print("===============SHOULD SHOW 7 BRANCHES=====================")
testDatabase.query_all_branches()
print("==========================================================")

testDatabase.insert_listing("Apples", "good apples", "1", "Cold Storage", "3", "")
testDatabase.insert_listing("Apples2", "good apples", "2", "Cold Storage", "3", "")
testDatabase.insert_listing("Apples3", "good apples", "3", "Fairprice Finest", "4", "")
testDatabase.insert_listing("Apples4", "good apples", "4", "Fairprice Finest", "4", "")
testDatabase.insert_listing("Apples5", "good apples", "5", "Sheng Siong", "5", "")
testDatabase.insert_listing("Apples6", "good apples", "6", "Sheng Siong", "5", "")
print("===============SHOULD SHOW 6 LISTINGS=====================")
testDatabase.query_all_listings()
print("===========================================================")

print("============Listings in BUGIS================")
testDatabase.query_listing_area('Bugis')
print("===========================================================")
print("")
print("=============3 Listings between 1 and 3=======")
testDatabase.query_price_details(1, 3)
print("=============3 Listings between 4 and 6=======")
testDatabase.query_price_details(4, 6)

print("")

print("=====3 Listings from Bugis Branch=============")
branchID = testDatabase.query_branchID("Fairprice Finest", "Bugis Branch")
testDatabase.query_branch_listings(branchID)

print("======= SHOULD HAVE NO MORE LISTINGS ===========")
testDatabase.delete_listing("1")
testDatabase.delete_listing("2")
testDatabase.delete_listing("3")
testDatabase.delete_listing("4")
testDatabase.delete_listing("5")
testDatabase.delete_listing("6")
testDatabase.query_all_listings()